# src/downloader/mbtiles_handler.py

import time
import threading
import queue
import sqlite3
from pathlib import Path
from queue import Queue, Empty
from loguru import logger

from .connection_pool import ConnectionPool
from .transaction import TransactionManager
from .utils import ensure_directory
from ..config import config_manager


class MBTilesHandler:
    """
    MBTiles 处理器：负责 MBTiles 相关的操作
    """

    def __init__(self, downloader):
        """
        初始化 MBTiles 处理器
        
        Args:
            downloader: TileDownloader 实例
        """
        self.downloader = downloader
        self.output_path = Path(downloader.output_dir)
        self.save_format = downloader.save_format
        self.scheme = downloader.scheme
        self.provider = downloader.provider
        self.is_mbtiles = downloader.is_mbtiles
        self.enable_sharding = downloader.enable_sharding
        
        # MBTiles相关
        self.mbtiles_conn = None
        self.mbtiles_cursor = None
        self.mbtiles_write_queue = Queue(maxsize=10000)  # 设置队列大小限制
        self.mbtiles_writer_thread = None
        self.mbtiles_writer_stop_event = threading.Event()
        self.mbtiles_batch_size = config_manager.get("download.mbtiles_batch_size", 100)
        self.mbtiles_paths = {}
        
        # 事务管理和连接池
        self.transaction_manager = TransactionManager()
        self.connection_pool = ConnectionPool()
        
        # 初始化 MBTiles
        if self.is_mbtiles and not self.enable_sharding:
            self._init_mbtiles()
            
        # 启动 MBTiles 写入线程
        if self.is_mbtiles:
            self._start_mbtiles_writer()

    def _init_mbtiles(self):
        """
        初始化MBTiles数据库，创建所需的表结构
        """
        max_retries = 5
        retry_delay = 1

        for attempt in range(max_retries):
            try:
                self.mbtiles_conn = sqlite3.connect(self.output_path, check_same_thread=False)
                self.mbtiles_cursor = self.mbtiles_conn.cursor()

                self.mbtiles_conn.execute('PRAGMA journal_mode=WAL;')
                self.mbtiles_conn.execute('PRAGMA cache_size=2000000;')
                self.mbtiles_conn.execute('PRAGMA synchronous=NORMAL;')
                self.mbtiles_conn.execute('PRAGMA enable_shared_cache=1;')
                self.mbtiles_conn.execute('PRAGMA wal_autocheckpoint=5000;')
                self.mbtiles_conn.execute('PRAGMA busy_timeout=30000;')
                self.mbtiles_conn.execute('PRAGMA temp_store=MEMORY;')
                self.mbtiles_conn.execute('PRAGMA mmap_size=536870912;')
                self.mbtiles_conn.execute('PRAGMA auto_vacuum=NONE;')
                self.mbtiles_conn.execute('PRAGMA foreign_keys=OFF;')

                self.mbtiles_cursor.execute('''
                    CREATE TABLE IF NOT EXISTS tiles (
                        zoom_level INTEGER,
                        tile_column INTEGER,
                        tile_row INTEGER,
                        tile_data BLOB,
                        PRIMARY KEY (zoom_level, tile_column, tile_row)
                    )
                ''')

                self.mbtiles_cursor.execute('''
                    CREATE TABLE IF NOT EXISTS metadata (
                        name TEXT,
                        value TEXT,
                        PRIMARY KEY (name)
                    )
                ''')

                metadata = [
                    ('name', 'TileHarvester'),
                    ('type', 'baselayer'),
                    ('version', '1.0'),
                    ('description', 'Generated by TileHarvester'),
                    ('format', self.provider.extension),
                    ('scheme', self.scheme),
                ]

                self.mbtiles_cursor.executemany(
                    'INSERT OR REPLACE INTO metadata (name, value) VALUES (?, ?)',
                    metadata
                )

                self.mbtiles_conn.commit()

                logger.info(f"MBTiles数据库初始化完成: {self.output_path}")
                return
            except sqlite3.OperationalError as e:
                if "database is locked" in str(e):
                    logger.warning(f"MBTiles数据库被锁定，尝试重试 ({attempt+1}/{max_retries})...")
                    if self.mbtiles_conn:
                        try:
                            self.mbtiles_conn.close()
                        except:
                            pass
                    time.sleep(retry_delay)
                    retry_delay *= 2
                else:
                    logger.error(f"MBTiles数据库初始化失败: {e}")
                    if self.mbtiles_conn:
                        try:
                            self.mbtiles_conn.close()
                        except:
                            pass
                    raise
            except Exception as e:
                logger.error(f"MBTiles数据库初始化失败: {e}")
                if self.mbtiles_conn:
                    try:
                        self.mbtiles_conn.close()
                    except:
                        pass
                raise

        logger.error(f"MBTiles数据库初始化失败: 经过 {max_retries} 次尝试后仍然无法获取数据库锁")
        raise Exception(f"经过 {max_retries} 次尝试后仍然无法获取数据库锁")

    def _start_mbtiles_writer(self):
        """
        启动MBTiles写入线程
        """
        self.mbtiles_writer_stop_event.clear()

        self.mbtiles_writer_thread = threading.Thread(
            target=self._mbtiles_writer,
            name="MBTilesWriter"
        )
        self.mbtiles_writer_thread.daemon = True
        self.mbtiles_writer_thread.start()

        logger.info("MBTiles写入线程已启动")

    def _stop_mbtiles_writer(self):
        """
        停止MBTiles写入线程
        """
        if self.mbtiles_writer_thread and self.mbtiles_writer_thread.is_alive():
            self.mbtiles_writer_stop_event.set()
            self.mbtiles_write_queue.put(None)
            self.mbtiles_writer_thread.join(timeout=5)
            logger.info("MBTiles写入线程已停止")

    def _mbtiles_writer(self):
        """
        MBTiles写入线程的主逻辑
        """
        thread_name = threading.current_thread().name
        logger.info(f"{thread_name} 启动")

        batch_buffer = {}

        try:
            while not self.mbtiles_writer_stop_event.is_set():
                try:
                    task = self.mbtiles_write_queue.get(timeout=1)
                    if task is None:
                        break

                    z, x, mbtiles_row, tile_data = task

                    if z not in batch_buffer:
                        batch_buffer[z] = []
                    batch_buffer[z].append((x, mbtiles_row, tile_data))

                    for zoom, tiles in list(batch_buffer.items()):
                        if len(tiles) >= self.mbtiles_batch_size:
                            self._batch_write_mbtiles(zoom, tiles)
                            batch_buffer[zoom] = []

                except Empty:
                    for zoom, tiles in list(batch_buffer.items()):
                        if tiles:
                            self._batch_write_mbtiles(zoom, tiles)
                            batch_buffer[zoom] = []
                    continue
                except Exception as e:
                    logger.error(f"{thread_name} - 处理写入任务失败: {e}")
                    import traceback
                    traceback.print_exc()
                    continue
        except Exception as e:
            logger.error(f"{thread_name} - 线程异常: {e}")
            import traceback
            traceback.print_exc()
        finally:
            for zoom, tiles in list(batch_buffer.items()):
                if tiles:
                    try:
                        self._batch_write_mbtiles(zoom, tiles)
                    except Exception as e:
                        logger.error(f"{thread_name} - 写入剩余数据失败: {e}")

            logger.info(f"{thread_name} 结束")

    def _batch_write_mbtiles(self, zoom, tiles):
        """
        批量写入MBTiles数据
        """
        if not tiles:
            return

        # 优化：将数据分批次写入，每批次最多100条，与老版本保持一致
        batch_size = 100
        total_written = 0
        
        try:
            for i in range(0, len(tiles), batch_size):
                batch = tiles[i:i+batch_size]
                
                if self.enable_sharding:
                    mbtiles_conn = self._get_mbtiles_connection(zoom)
                    mbtiles_conn.executemany(
                        '''INSERT OR REPLACE INTO tiles
                        (zoom_level, tile_column, tile_row, tile_data)
                        VALUES (?, ?, ?, ?)''',
                        [(zoom, x, row, data) for x, row, data in batch]
                    )
                    # 使用事务管理器判断是否需要提交
                    if self.transaction_manager.should_commit():
                        self.transaction_manager.commit(mbtiles_conn, zoom)
                else:
                    if self.mbtiles_conn:
                        self.mbtiles_conn.executemany(
                            '''INSERT OR REPLACE INTO tiles
                            (zoom_level, tile_column, tile_row, tile_data)
                            VALUES (?, ?, ?, ?)''',
                            [(zoom, x, row, data) for x, row, data in batch]
                        )
                        # 使用事务管理器判断是否需要提交
                        if self.transaction_manager.should_commit():
                            self.transaction_manager.commit(self.mbtiles_conn)
                
                total_written += len(batch)
                
                # 移除休眠，提高写入速度

            # 确保所有数据都被提交
            if self.enable_sharding:
                mbtiles_conn = self._get_mbtiles_connection(zoom)
                self.transaction_manager.commit(mbtiles_conn, zoom)
            else:
                if self.mbtiles_conn:
                    self.transaction_manager.commit(self.mbtiles_conn)

            logger.debug(f"批量写入 {total_written} 个瓦片到MBTiles (zoom={zoom})")
        except sqlite3.OperationalError as e:
            if "database is locked" in str(e):
                logger.warning(f"MBTiles数据库被锁定，尝试重试...")
                time.sleep(0.1)
                self._batch_write_mbtiles(zoom, tiles)
            else:
                logger.error(f"批量写入MBTiles失败: {e}")
        except Exception as e:
            logger.error(f"批量写入MBTiles失败: {e}")

    def _get_mbtiles_connection(self, zoom):
        """
        根据缩放级别获取对应的MBTiles连接，每个线程使用独立的连接
        """
        thread_id = threading.get_ident()
        pool_key = (thread_id, zoom)

        mbtiles_path = Path(str(self.output_path).replace("{z}", str(zoom)))
        self.mbtiles_paths[zoom] = mbtiles_path

        ensure_directory(mbtiles_path.parent)

        # 使用连接池获取连接
        conn = self.connection_pool.get_connection(pool_key, mbtiles_path)

        # 初始化数据库表结构
        try:
            cursor = conn.cursor()
            cursor.execute('''
                CREATE TABLE IF NOT EXISTS tiles (
                    zoom_level INTEGER,
                    tile_column INTEGER,
                    tile_row INTEGER,
                    tile_data BLOB,
                    PRIMARY KEY (zoom_level, tile_column, tile_row)
                )
            ''')
            cursor.execute('''
                CREATE TABLE IF NOT EXISTS metadata (
                    name TEXT,
                    value TEXT,
                    PRIMARY KEY (name)
                )
            ''')

            metadata = [
                ('name', 'TileHarvester'),
                ('type', 'baselayer'),
                ('version', '1.0'),
                ('description', f'Generated by TileHarvester for zoom level {zoom}'),
                ('format', self.provider.extension),
                ('scheme', self.scheme),
            ]
            cursor.executemany(
                'INSERT OR REPLACE INTO metadata (name, value) VALUES (?, ?)',
                metadata
            )

            conn.commit()

            logger.debug(f"线程 {thread_id} 初始化MBTiles数据库连接: {mbtiles_path}")
        except Exception as e:
            logger.error(f"MBTiles数据库初始化失败: {e}")
            raise

        return conn

    def _finalize_download(self):
        """
        完成下载，确保所有事务都已提交
        """
        if self.is_mbtiles:
            if self.enable_sharding:
                for zoom, conn in self.connection_pool.connections.items():
                    try:
                        self.transaction_manager.commit(conn, zoom)
                    except Exception as e:
                        logger.error(f"提交MBTiles事务失败: {e}")
            else:
                if self.mbtiles_conn:
                    try:
                        self.transaction_manager.commit(self.mbtiles_conn)
                    except Exception as e:
                        logger.error(f"提交MBTiles事务失败: {e}")

        self.transaction_manager.reset()
        logger.debug("重置事务计数器")

    def close(self):
        """
        关闭 MBTiles 相关资源
        """
        # 停止 MBTiles 写入线程
        self._stop_mbtiles_writer()
        
        # 关闭连接池
        try:
            self.connection_pool.close_all_connections()
            logger.debug("关闭 MBTiles 连接池")
        except Exception as e:
            logger.error(f"关闭 MBTiles 连接池失败: {e}")
        
        # 关闭 MBTiles 连接
        if self.mbtiles_conn:
            try:
                self.mbtiles_conn.close()
                logger.debug("关闭 MBTiles 连接")
            except Exception as e:
                logger.error(f"关闭 MBTiles 连接失败: {e}")
