# src/downloader/mbtiles_handler.py

import time
import threading
import sqlite3
from pathlib import Path

from loguru import logger

from .connection_pool import ConnectionPool
from .utils import ensure_directory
from ..config import config_manager

_TILES_TABLE_SQL = '''
    CREATE TABLE IF NOT EXISTS tiles (
        zoom_level INTEGER,
        tile_column INTEGER,
        tile_row INTEGER,
        tile_data BLOB,
        PRIMARY KEY (zoom_level, tile_column, tile_row)
    )
'''

_METADATA_TABLE_SQL = '''
    CREATE TABLE IF NOT EXISTS metadata (
        name TEXT,
        value TEXT,
        PRIMARY KEY (name)
    )
'''


class MBTilesHandler:
    """
    MBTiles 处理器：负责把下载线程产生的瓦片异步写入 MBTiles 数据库。

    生产/消费模型：
    * 下载线程把 (z, x, mbtiles_row, data) 放入 ``downloader.mbtiles_write_queue``；
    * 单个写入线程批量消费该队列并写库，避免多线程同时写 SQLite 造成锁竞争。

    注意：写入队列与下载器共享同一个对象，这是旧版本的关键缺陷
    （生产者与消费者使用了两个不同的队列，导致瓦片从未落库）。
    """

    def __init__(self, downloader):
        self.downloader = downloader
        self.output_path = Path(downloader.output_dir)
        self.scheme = downloader.scheme
        self.provider = downloader.provider
        self.is_mbtiles = downloader.is_mbtiles
        self.enable_sharding = downloader.enable_sharding

        # 与下载器共用同一个写队列
        self.mbtiles_write_queue = downloader.mbtiles_write_queue
        self.mbtiles_batch_size = int(
            config_manager.get("download.mbtiles_batch_size", 500)
        )
        self.mbtiles_paths = {}
        self._initialized_paths = set()
        self._closed = False

        # 非分库模式下的单连接（仅写入线程使用）
        self.mbtiles_conn = None

        # 分库模式下按 zoom 使用独立连接
        self.connection_pool = ConnectionPool()

        if self.is_mbtiles and not self.enable_sharding:
            self._init_mbtiles()

        if self.is_mbtiles:
            self._start_mbtiles_writer()

    # ------------------------------------------------------------------ #
    # 初始化
    # ------------------------------------------------------------------ #
    def _init_mbtiles(self):
        """初始化非分库 MBTiles 数据库及表结构。"""
        max_retries = 5
        retry_delay = 1

        for attempt in range(max_retries):
            try:
                self.mbtiles_conn = sqlite3.connect(self.output_path, check_same_thread=False)
                self._configure_connection(self.mbtiles_conn)
                self._ensure_schema(self.mbtiles_conn)
                logger.info(f"MBTiles数据库初始化完成: {self.output_path}")
                return
            except sqlite3.OperationalError as e:
                self._safe_close(self.mbtiles_conn)
                self.mbtiles_conn = None
                if "database is locked" in str(e) and attempt < max_retries - 1:
                    logger.warning(f"MBTiles数据库被锁定，重试 ({attempt + 1}/{max_retries})...")
                    time.sleep(retry_delay)
                    retry_delay *= 2
                else:
                    logger.error(f"MBTiles数据库初始化失败: {e}")
                    raise
            except Exception as e:  # noqa: BLE001
                self._safe_close(self.mbtiles_conn)
                self.mbtiles_conn = None
                logger.error(f"MBTiles数据库初始化失败: {e}")
                raise

    @staticmethod
    def _configure_connection(conn: sqlite3.Connection):
        """为 SQLite 连接设置适合批量写入的参数。"""
        for pragma in (
            'PRAGMA journal_mode=WAL;',
            'PRAGMA cache_size=2000000;',
            'PRAGMA synchronous=NORMAL;',
            'PRAGMA wal_autocheckpoint=5000;',
            'PRAGMA busy_timeout=30000;',
            'PRAGMA temp_store=MEMORY;',
            'PRAGMA mmap_size=536870912;',
            'PRAGMA auto_vacuum=NONE;',
            'PRAGMA foreign_keys=OFF;',
        ):
            try:
                conn.execute(pragma)
            except sqlite3.Error:
                # 个别 pragma 在部分 SQLite 版本不可用，忽略即可
                pass

    def _ensure_schema(self, conn: sqlite3.Connection, zoom=None):
        """创建 tiles / metadata 表并写入基础元数据。"""
        cursor = conn.cursor()
        cursor.execute(_TILES_TABLE_SQL)
        cursor.execute(_METADATA_TABLE_SQL)

        description = 'Generated by TileScraper'
        if zoom is not None:
            description = f'Generated by TileScraper for zoom level {zoom}'

        metadata = [
            ('name', 'TileScraper'),
            ('type', 'baselayer'),
            ('version', '1.0'),
            ('description', description),
            ('format', self.provider.extension),
            ('scheme', self.scheme),
        ]
        cursor.executemany(
            'INSERT OR REPLACE INTO metadata (name, value) VALUES (?, ?)',
            metadata,
        )
        conn.commit()

    # ------------------------------------------------------------------ #
    # 写入线程
    # ------------------------------------------------------------------ #
    def _start_mbtiles_writer(self):
        """启动 MBTiles 写入线程。"""
        self.mbtiles_writer_stop_event = threading.Event()
        self.mbtiles_writer_thread = threading.Thread(
            target=self._mbtiles_writer, name="MBTilesWriter", daemon=True
        )
        self.mbtiles_writer_thread.start()
        logger.info("MBTiles写入线程已启动")

    def _stop_mbtiles_writer(self):
        """停止 MBTiles 写入线程（先确保队列已排空）。"""
        if self.mbtiles_writer_thread and self.mbtiles_writer_thread.is_alive():
            self.mbtiles_writer_stop_event.set()
            self.mbtiles_write_queue.put(None)
            self.mbtiles_writer_thread.join(timeout=5)
            logger.info("MBTiles写入线程已停止")

    def _mbtiles_writer(self):
        """写线程主体：批量消费写队列。"""
        name = threading.current_thread().name
        logger.debug(f"{name} 启动")
        buffers = {}

        while not self.mbtiles_writer_stop_event.is_set():
            try:
                task = self.mbtiles_write_queue.get(timeout=1)
            except Exception:
                # 超时空闲：把缓冲区里剩余的瓦片刷盘
                self._flush_all(buffers)
                continue

            try:
                if task is None:
                    self._flush_all(buffers)
                    break
                z, x, row, data = task
                buffers.setdefault(z, []).append((x, row, data))
                if len(buffers[z]) >= self.mbtiles_batch_size:
                    self._write_batch(z, buffers[z])
                    buffers[z] = []
                # 队列空了就把剩余数据刷盘（task_done 之前完成，便于 join 语义）
                if self.mbtiles_write_queue.empty():
                    self._flush_all(buffers)
            except Exception as e:  # noqa: BLE001
                logger.error(f"{name} - 写入任务失败: {e}")
                import traceback
                traceback.print_exc()
            finally:
                self.mbtiles_write_queue.task_done()

        self._flush_all(buffers)
        logger.debug(f"{name} 结束")

    def _flush_all(self, buffers: dict):
        """把各 zoom 缓冲区的剩余瓦片全部写盘。"""
        for zoom, tiles in list(buffers.items()):
            if tiles:
                self._write_batch(zoom, tiles)
                buffers[zoom] = []

    def _write_batch(self, zoom: int, tiles: list):
        """把一批瓦片写入对应 zoom 的 MBTiles 并提交。"""
        if not tiles:
            return
        rows = [(zoom, x, row, data) for x, row, data in tiles]
        try:
            if self.enable_sharding:
                conn = self._get_mbtiles_connection(zoom)
                conn.executemany(
                    'INSERT OR REPLACE INTO tiles '
                    '(zoom_level, tile_column, tile_row, tile_data) VALUES (?, ?, ?, ?)',
                    rows,
                )
                conn.commit()
            elif self.mbtiles_conn:
                self.mbtiles_conn.executemany(
                    'INSERT OR REPLACE INTO tiles '
                    '(zoom_level, tile_column, tile_row, tile_data) VALUES (?, ?, ?, ?)',
                    rows,
                )
                self.mbtiles_conn.commit()
        except sqlite3.OperationalError as e:
            if "database is locked" in str(e):
                logger.warning("MBTiles数据库被锁定，稍后重试...")
                time.sleep(0.2)
                self._write_batch(zoom, tiles)
            else:
                logger.error(f"批量写入MBTiles失败: {e}")
        except Exception as e:  # noqa: BLE001
            logger.error(f"批量写入MBTiles失败: {e}")

    def _get_mbtiles_connection(self, zoom: int) -> sqlite3.Connection:
        """分库模式下按 zoom 获取连接（仅写线程调用）。"""
        thread_id = threading.get_ident()
        pool_key = (thread_id, zoom)
        mbtiles_path = Path(str(self.output_path).replace("{z}", str(zoom)))
        self.mbtiles_paths[zoom] = mbtiles_path
        ensure_directory(mbtiles_path.parent)

        conn = self.connection_pool.get_connection(pool_key, mbtiles_path)
        if mbtiles_path not in self._initialized_paths:
            self._ensure_schema(conn, zoom=zoom)
            self._initialized_paths.add(mbtiles_path)
        return conn

    # ------------------------------------------------------------------ #
    # 收尾
    # ------------------------------------------------------------------ #
    def wait_drained(self, timeout: float = 600):
        """等待写队列被完全消费并落盘。"""
        deadline = time.time() + timeout
        while self.mbtiles_write_queue.unfinished_tasks > 0 and time.time() < deadline:
            time.sleep(0.05)

    def finalize(self):
        """等待所有瓦片落盘并提交事务。"""
        self.wait_drained()
        try:
            if self.enable_sharding:
                for conn in list(self.connection_pool.connections.values()):
                    conn.commit()
            elif self.mbtiles_conn:
                self.mbtiles_conn.commit()
        except Exception as e:  # noqa: BLE001
            logger.error(f"提交 MBTiles 事务失败: {e}")

    def close(self):
        """关闭写入线程与数据库连接（幂等）。"""
        if self._closed:
            return
        self._closed = True

        if self.is_mbtiles:
            self.wait_drained()
            self.finalize()
            self._stop_mbtiles_writer()

        try:
            self.connection_pool.close_all_connections()
        except Exception as e:  # noqa: BLE001
            logger.error(f"关闭 MBTiles 连接池失败: {e}")

        self._safe_close(self.mbtiles_conn)
        self.mbtiles_conn = None

    @staticmethod
    def _safe_close(conn):
        if conn is None:
            return
        try:
            conn.close()
        except Exception:
            pass
