# src/downloader/mbtiles.py

import sqlite3
import time
from pathlib import Path
from typing import Dict, Optional
from loguru import logger
from .connection_pool import ConnectionPool


class MBTilesManager:
    """
    MBTiles文件管理器：负责MBTiles文件的创建、初始化和管理
    """

    def __init__(self, output_path: str, scheme: str = "xyz"):
        """
        初始化MBTiles管理器
        
        Args:
            output_path: MBTiles文件路径
            scheme: 瓦片坐标系，默认xyz
        """
        self.output_path = output_path
        self.scheme = scheme
        self.mbtiles_paths = {}
        self.mbtiles_connections = {}
        self.connection_pool = ConnectionPool()

    def get_mbtiles_connection(self, zoom: int):
        """
        根据缩放级别获取对应的MBTiles连接，每个线程使用独立的连接
        
        Args:
            zoom: 缩放级别
            
        Returns:
            sqlite3.Connection: MBTiles数据库连接
        """
        import threading
        thread_id = threading.get_ident()
        pool_key = (thread_id, zoom)
        
        # 构建当前缩放级别的MBTiles文件路径
        mbtiles_path = Path(str(self.output_path).replace("{z}", str(zoom)))
        self.mbtiles_paths[zoom] = mbtiles_path
        
        # 确保输出目录存在
        from .utils import ensure_directory
        ensure_directory(mbtiles_path.parent)
        
        # 从连接池获取连接
        conn = self.connection_pool.get_connection(pool_key, mbtiles_path)
        
        # 初始化数据库表结构
        try:
            cursor = conn.cursor()
            cursor.execute('''
                CREATE TABLE IF NOT EXISTS tiles (
                    zoom_level INTEGER,
                    tile_column INTEGER,
                    tile_row INTEGER,
                    tile_data BLOB,
                    PRIMARY KEY (zoom_level, tile_column, tile_row)
                )
            ''')
            cursor.execute('''
                CREATE TABLE IF NOT EXISTS metadata (
                    name TEXT,
                    value TEXT,
                    PRIMARY KEY (name)
                )
            ''')
            
            # 插入基本metadata
            metadata = [
                ('name', 'TileHarvester'),
                ('type', 'baselayer'),
                ('version', '1.0'),
                ('description', f'Generated by TileHarvester for zoom level {zoom}'),
                ('format', 'jpg'),  # 默认格式，后续会根据实际情况更新
                ('scheme', self.scheme),
            ]
            cursor.executemany(
                'INSERT OR REPLACE INTO metadata (name, value) VALUES (?, ?)',
                metadata
            )
            
            conn.commit()
            
            logger.debug(f"线程 {thread_id} 初始化MBTiles数据库连接: {mbtiles_path}")
        except Exception as e:
            logger.error(f"MBTiles数据库初始化失败: {e}")
            raise
        
        return conn

    def close_connections(self):
        """
        关闭所有MBTiles连接
        """
        # 使用连接池的方法关闭所有连接
        self.connection_pool.close_all_connections()
        logger.debug("关闭所有MBTiles连接")

    def finalize_download(self):
        """
        完成下载，确保所有事务都已提交
        """
        # 注意：连接池的close_all_connections方法会自动提交所有事务
        # 这里不需要额外的操作，因为在下载完成时会调用close_connections
        logger.debug("完成MBTiles下载，所有事务将在关闭连接时提交")
